// frontend/src/routes/login/+page.svelte
<script lang="ts">
import { api } from '$lib/api';

let email = $state('');
let password = $state('');
let error = $state('');
let submitting = $state(false);

async function submit() {
	error = '';
	submitting = true;
	try {
		await api.login(email, password);
		window.location.assign('/dashboard');
	} catch (reason) {
		error = reason instanceof Error ? reason.message : 'Login failed';
	} finally {
		submitting = false;
	}
}
</script>

<main><form onsubmit={(event) => { event.preventDefault(); submit(); }}><h1>Login</h1>{#if error}<p class="error" role="alert">{error}</p>{/if}<label>Email <input bind:value={email} type="email" autocomplete="email" required /></label><label>Password <input bind:value={password} type="password" autocomplete="current-password" required /></label><button type="submit" disabled={submitting}>{submitting ? 'Logging in…' : 'Login'}</button><p>No account? <a href="/register">Register</a></p></form></main>

// src/app/login/page.tsx
'use client';

import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useState } from 'react';
import { ErrorBanner } from '@/components/ErrorBanner';
import { useAuth } from '@/lib/auth-context';

export default function LoginPage() {
	const [email, setEmail] = useState('');
	const [password, setPassword] = useState('');
	const [error, setError] = useState('');
	const { login } = useAuth();
	const router = useRouter();

	async function handleSubmit(e: React.FormEvent) {
		e.preventDefault();
		setError('');
		try {
			await login(email, password);
			router.push('/dashboard');
		} catch (err) {
			setError(err instanceof Error ? err.message : 'Login failed');
		}
	}

	return (
		<main className="flex min-h-screen items-center justify-center">
			<form onSubmit={handleSubmit} className="w-full max-w-sm space-y-4">
				<h1 className="text-2xl font-bold">Login</h1>
				{error && <ErrorBanner message={error} />}
				<input
					type="email"
					placeholder="Email"
					value={email}
					onChange={(e) => setEmail(e.target.value)}
					required
					className="w-full rounded border border-input bg-background px-3 py-2"
				/>
				<input
					type="password"
					placeholder="Password"
					value={password}
					onChange={(e) => setPassword(e.target.value)}
					required
					className="w-full rounded border border-input bg-background px-3 py-2"
				/>
				<button type="submit" className="w-full rounded bg-primary px-4 py-2 text-primary-foreground">
					Login
				</button>
				<p className="text-sm text-muted-foreground">
					No account?{' '}
					<Link href="/register" className="text-primary underline">
						Register
					</Link>
				</p>
			</form>
		</main>
	);
}
