// src/routes/register/+page.svelte
<script lang="ts">
	import { register } from '$lib/stores/auth';
	import { goto } from '$app/navigation';

	let email = $state('');
	let password = $state('');
	let confirmPassword = $state('');
	let error = $state('');
	let submitting = $state(false);

	async function handleSubmit(e: SubmitEvent) {
		e.preventDefault();
		error = '';

		if (password !== confirmPassword) {
			error = 'Passwords do not match';
			return;
		}

		if (password.length < 8) {
			error = 'Password must be at least 8 characters';
			return;
		}

		submitting = true;
		const result = await register(email, password);
		submitting = false;

		if (result) {
			error = result;
		} else {
			goto('/dashboard');
		}
	}
</script>

<main class="flex min-h-screen items-center justify-center bg-gray-50">
	<div class="w-full max-w-md space-y-6 rounded-lg bg-white p-8 shadow">
		<h1 class="text-center text-2xl font-bold text-gray-900">Register</h1>

		{#if error}
			<p class="rounded-md bg-red-50 p-3 text-sm text-red-600">{error}</p>
		{/if}

		<form onsubmit={handleSubmit} class="space-y-4">
			<div>
				<label for="email" class="block text-sm font-medium text-gray-700">Email</label>
				<input
					id="email"
					type="email"
					bind:value={email}
					required
					class="mt-1 block w-full rounded-md border border-gray-300 px-3 py-2 shadow-sm focus:border-blue-500 focus:ring-blue-500 focus:outline-none"
				/>
			</div>

			<div>
				<label for="password" class="block text-sm font-medium text-gray-700">Password</label>
				<input
					id="password"
					type="password"
					bind:value={password}
					required
					minlength="8"
					class="mt-1 block w-full rounded-md border border-gray-300 px-3 py-2 shadow-sm focus:border-blue-500 focus:ring-blue-500 focus:outline-none"
				/>
			</div>

			<div>
				<label for="confirm-password" class="block text-sm font-medium text-gray-700">Confirm Password</label>
				<input
					id="confirm-password"
					type="password"
					bind:value={confirmPassword}
					required
					class="mt-1 block w-full rounded-md border border-gray-300 px-3 py-2 shadow-sm focus:border-blue-500 focus:ring-blue-500 focus:outline-none"
				/>
			</div>

			<button
				type="submit"
				disabled={submitting}
				class="w-full rounded-md bg-blue-600 px-4 py-2 text-white hover:bg-blue-700 disabled:opacity-50"
			>
				{submitting ? 'Creating account...' : 'Register'}
			</button>
		</form>

		<p class="text-center text-sm text-gray-600">
			Already have an account? <a href="/login" class="text-blue-600 hover:underline">Login</a>
		</p>
	</div>
</main>

// src/app/register/page.tsx
'use client';

import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useState } from 'react';
import { ErrorBanner } from '@/components/ErrorBanner';
import { useAuth } from '@/lib/auth-context';

export default function RegisterPage() {
	const [email, setEmail] = useState('');
	const [password, setPassword] = useState('');
	const [error, setError] = useState('');
	const { register } = useAuth();
	const router = useRouter();

	async function handleSubmit(e: React.FormEvent) {
		e.preventDefault();
		setError('');
		try {
			await register(email, password);
			router.push('/dashboard');
		} catch (err) {
			setError(err instanceof Error ? err.message : 'Registration failed');
		}
	}

	return (
		<main className="flex min-h-screen items-center justify-center">
			<form onSubmit={handleSubmit} className="w-full max-w-sm space-y-4">
				<h1 className="text-2xl font-bold">Register</h1>
				{error && <ErrorBanner message={error} />}
				<input
					type="email"
					placeholder="Email"
					value={email}
					onChange={(e) => setEmail(e.target.value)}
					required
					className="w-full rounded border border-input bg-background px-3 py-2"
				/>
				<input
					type="password"
					placeholder="Password (min 8 characters)"
					value={password}
					onChange={(e) => setPassword(e.target.value)}
					required
					minLength={8}
					className="w-full rounded border border-input bg-background px-3 py-2"
				/>
				<button type="submit" className="w-full rounded bg-primary px-4 py-2 text-primary-foreground">
					Register
				</button>
				<p className="text-sm text-muted-foreground">
					Already have an account?{' '}
					<Link href="/login" className="text-primary underline">
						Login
					</Link>
				</p>
			</form>
		</main>
	);
}
